{% set name = "pytest-virtualenv" %}
{% set version = "1.8.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1bb6d4ad77d198ff19ba4259f78c685b24ec63a528037bc3a488f1c780bc6aa9

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - pip
    - pytest
    - pytest-fixture-config
    - pytest-shutil
    - python
    - setuptools
    - setuptools-git
  run:
    - pytest
    - pytest-fixture-config
    - pytest-shutil
    - python

test:
  imports:
    - pytest_virtualenv
  requires:
    - mock
    - pytest
    - pytest-shutil
    - pytest-fixture-config

about:
  home: https://github.com/manahl/pytest-plugins
  license: MIT
  license_family: MIT
  license_file: 'LICENSE'
  summary: Virtualenv fixture for py.test
  doc_url: https://github.com/manahl/pytest-plugins/tree/master/pytest-virtualenv#readme
  dev_url: https://github.com/manahl/pytest-plugins

extra:
  recipe-maintainers:
    - jcfr
