{% set name = "pytest-virtualenv" %}
{% set version = "1.8.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 54991039df31b23e82f59da2d08ab3ab809cf6eecf89905bdf2927a41f97e1c5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - pip
    - pytest
    - pytest-fixture-config
    - pytest-shutil
    - python
    - setuptools
    - setuptools-git
  run:
    - pytest
    - pytest-fixture-config
    - pytest-shutil
    - python

test:
  imports:
    - pytest_virtualenv
  requires:
    - mock
    - pytest
    - pytest-shutil
    - pytest-fixture-config

about:
  home: https://github.com/manahl/pytest-plugins
  license: MIT
  license_family: MIT
  license_file: 'LICENSE'
  summary: Virtualenv fixture for py.test
  doc_url: https://github.com/manahl/pytest-plugins/tree/master/pytest-virtualenv#readme
  dev_url: https://github.com/manahl/pytest-plugins

extra:
  recipe-maintainers:
    - jcfr
