{% set name = "pytest-virtualenv" %}
{% set version = "1.7.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2270ee8822111ec25db48e9d9f2efec32e68483a015b14cd0d92aeccc6ff820f

build:
  number: 1
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  host:
    - pip
    - pytest
    - pytest-fixture-config
    - pytest-shutil
    - python >=3
    - setuptools
    - setuptools-git
  run:
    - pytest
    - pytest-fixture-config
    - pytest-shutil
    - importlib-metadata
    - python >=3

test:
  imports:
    - pytest_virtualenv
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/man-group/pytest-plugins
  license: MIT
  license_family: MIT
  license_file: 'LICENSE'
  summary: Virtualenv fixture for py.test
  doc_url: https://github.com/man-group/pytest-plugins/tree/master/pytest-virtualenv#readme
  dev_url: https://github.com/man-group/pytest-plugins

extra:
  recipe-maintainers:
    - jcfr
    - henryiii
