travis:
  secure:
    BINSTAR_TOKEN: agIZwK3BPfq4qedetCbL3b0YMhRfkhx71FJxTXpLcCzi1WgF1Vbcpkn8eDQKbfgNs5vawqbsUz/ZqHAqwL0b4mbcEUeEnAqiJboC0NZ1XOep0BNEjFNtYp+vuk/tLxaq3GVEicU7t2t0aCTUKcXo4+qG53aO/6QP8zv2H0h5cr862y+Fu01Gk5f8MBDEQ9o8/pZZXu4L6hew5SSb8A0Upepxaj4iXRj1rHjFmZ8xXi1pqfB3ahpIs9t8h8pzJ71evd3Bn2CKakXfiJfWE7Bj5Y1xUdKhCJZOJgZ1bgXR72PN/n34NW0EzN8zUqy0Ab4RBkRqDKU/pUOoe0+rBM56Cp52UludmjTPGOT42wllHLueBfZWXvF4MNUWFgmULQICIiDY+Xb/N6VqWnjOeZIa9xJ+G7Cpk0I/woEXN50OZ424Cw+V7oPl1UVi9fbJHQ9YbbL0K+63Z6zY/IsqNl7k9EVe5s7NT5CY7cUs3+QiUfwxcFFy5hEl8c0TBteFurEdpr35Um+ZicrOh+Wl6saCiKQKBqNQcBqEhnLs6tXs0r3OkLS1bF9OKQuNTNpj5q7m5CCWT0BUh3XF6IcngsRXg+PI+5O3TOdXXWTyfzu3nO1EDZLjMLhCmBldqau2tKxL9+md+IFIh0qQKm/c2HWL1qUzRxR+wlQz1uCwCVVxQzw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
